# GitHub Template

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Container
      uses: actions/checkout@v4
    - name: Cache SBT deps
      uses: coursier/cache-action@v6
    - name: Setup Scala with SBT
      uses: coursier/setup-action@v1
      with:
        apps: sbt
    - name: Start Dynamic Stub
      run: sbt runDynamicStub
    - name: Start Static Stub
      run: sbt runStaticStub
    - name: Run tests
      run: sbt test
