# GitHub Template

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    container: sbtscala/scala-sbt:eclipse-temurin-17.0.4_1.7.1_3.2.0
    steps:
    - uses: actions/checkout@v3
    - name: Start HTTP Stub
      run: sbt "httpStub / run" && sbt test
